### ISSUE TITLE
Version 1.16.4?

### ISSUE THREAD

**Issue by fantahund** [FukkitMC/TaterBukkit#8]
Is an update to version 1.16.4 planned?

**Comment by Ueaj-Kerman** [comment]
we barely started

**Comment by BoogieMonster1O1** [comment]
> we barely started

you didnt even start

**Comment by Ueaj-Kerman** [comment]
shut

**Comment by BoogieMonster1O1** [comment]
> shut

no u

**Comment by hYdos** [comment]
no u

**Comment by CoolMineman** [comment]
yes

**Comment by BoogieMonster1O1** [comment]
reopen or bad

**Comment by fantahund** [comment]
D:

**Comment by fantahund** [comment]
that escalated quickly

**Comment by BoogieMonster1O1** [comment]
![yote](https://cdn.discordapp.com/emojis/701652437089648722.png)

**Comment by TheMadHau5** [comment]
tmh5 calls for a reopen :tiny_potato:

**Comment by ramidzkh** [comment]
I think we have exceeded the quota of messages in #github per month

**Comment by TheMadHau5** [comment]
:concern:

**Comment by BoogieMonster1O1** [comment]
status quo

**Comment by ramidzkh** [comment]
https://github.com/FukkitMC/CannedTater
